### ISSUE TITLE
Typo3 8.x Support

### ISSUE THREAD

**Issue by blacksph3re** [YAG-Gallery/yag#104]
Hello,

is it planned to add support for the new Typo3 LTS 8.x? This gallery is effectively the only usable gallery plugin, rendering the new LTS practically useless for creating websites.

Best, N

**Comment by daniellienert** [comment]
Hey @blacksph3re, 
thanks for asking. Already answered it in https://github.com/YAG-Gallery/yag/issues/99.

Cheers, 
Daniel
