### ISSUE TITLE
Tx_Yag_Domain_Model_Gallery does not resolve thumbAlbum correctly (uses own ID)

### ISSUE THREAD

**Issue by garvinhicking** [YAG-Gallery/yag#112]
Funny issue: Using recent TYPO3 7.6 with recent YAG, the images displayed for the Gallery overview (Backend&Frontend) show wrong images, and not the ones specified per gallery item.

We tracked this down to the Model Gallery.php, where thumbAlbum is defined:

````
/**
  * Holds an album which is used as thumbnail for gallery
  * 
  * @lazy
  * @var Tx_Yag_Domain_Model_Album $thumbAlbum
  */
protected $thumbAlbum;
````

When we debugged the getThumbAlbum() method, we found out that for $this->thumbAlbum it always resolved to an object with the same UID as the gallery item UID.

We have patched it like this:

````
/**
  * Holds an album which is used as thumbnail for gallery
  * 
  * @var int $thumbAlbum
  */
protected $thumbAlbum;

public function getThumbAlbum()
     {
         $albumRepository = 
$this->objectManager->get('Tx_Yag_Domain_Repository_AlbumRepository'); 
/* @var $albumRepository Tx_Yag_Domain_Repository_AlbumRepository */
         $album = $albumRepository->findByUid($this->thumbAlbum);

         if (!($album instanceof Tx_Yag_Domain_Model_Album)) {
             if ($this->albums->count() > 0) {
                 $album = $this->albums->current();
             }
         }

         return $album;
     }
````

So we now use the actual integer stored in the database and it works. Could this be some kind of bug together with Extbase / Lazy loading itself?

**Comment by dominikmuellerwf** [comment]
Have the same issue, album thumbs in gallery view are not the right ones. The fix from garvinhicking does not work for me :-(

**Comment by garvinhicking** [comment]
@bobbel78 - you did purge your backend cache after you patched the file, yes?

**Comment by dominikmuellerwf** [comment]
I purged all caches via install tool.
