### ISSUE TITLE
Cluttered Layout in "Images Overview" in TYPO3 7.4

### ISSUE THREAD

**Issue by wowawebdesign** [YAG-Gallery/yag#42]
Small layout problem in the "Images overview" in TYPO3 7.4
![yag-problem](https://cloud.githubusercontent.com/assets/343511/9294876/849015fa-445a-11e5-8ffc-a6720e2f384e.png)

**Comment by daniellienert** [comment]
Ah :) Seems you have to run a `git submodule update --init --recursive` in the YAG folder.

**Comment by wowawebdesign** [comment]
Yes, now it works ;)
