### ISSUE TITLE
TYPO3 7.4 - Source selection: the server responded with a status of 500 ((AJAX))

### ISSUE THREAD

**Issue by slowhand11** [YAG-Gallery/yag#44]
Cant select gallery, gallery selector stays with classes inactiveSelectorBox selectorBoxBusy.
Console: 
the server responded with a status of 500 ((AJAX))
http://typo3.p272480.mittwaldserver.info/typo3/ajax.php?ajaxID=txyagM1::getGalleryList&yagPid=36&PID=18 Failed to load resource: the server responded with a status of 500 ((AJAX))

<t3err>
No backend function registered for ajaxID "txyagM1::getGalleryList".
</t3err>

**Comment by daniellienert** [comment]
Would you give me some more details?
Which TYPO3 Version do you use?
Where - on which page, at what action - do you encounter this issue?

**Comment by slowhand11** [comment]
TYPO3 version 7.4.0.
Using VHS, FLUX, fluidbackend, powermail, go_maps_ext

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/5380418/9953116/0dc8a80e-5dde-11e5-8182-bcbbad096f05.jpg)

No specific action, Gallery list is just not loading.

**Comment by slowhand11** [comment]
YAG version 4.0.6

**Comment by cdominpxp** [comment]
We have exactly the same problem here with Typo3 7.4.0 and YAG 4.0.6.

**Comment by matt-rein** [comment]
same here.
also typo3 7.4 and YAG 4.0.6

**Comment by metaxos** [comment]
also the same issue. typo3 7.4 and YAG 4.0.6

**Comment by johannesrusch** [comment]
Same here. TYPO3 7.4 and YAG 4.0.6
Tried it on multiple systems and setups. Picture is similar to slowhand11's pic.
@cdominpxp How exactly did you write the Ajax call?
@daniellienert Could it be, that pt_extlist and pt_extbase are the problem? Since they're not officially compatible with TYPO3 7.4...

**Comment by daniellienert** [comment]
Hey guys,
would you post, which PHP version you use? Could it be, that you use a pre 5.5 version?
Would you also check the latest master version - is the problem fixed?

cheers,
Daniel

**Comment by metaxos** [comment]
Hi there.
I'm using MAMP with 5.5.26.

regards

**Comment by daniellienert** [comment]
Ok ... thanks - seems that was a wrong lead ;(

**Comment by matt-rein** [comment]
Php 5.6.2


Von meinem iPad gesendet

**Comment by johannesrusch** [comment]
Tried PHP 5.6.6 on a LAMP (Perfect Server) and PHP 5.6.10 on a Mittwald test environment. And I tried both, the latest master (without your last commit on php5.5) and the 4.0.6 Version from the TER.

**Comment by slowhand11** [comment]
running on php 5.6.10 and tried latest master. Still not working. 
Maybee ajax call from cdominpxp is an solution?

**Comment by slowhand11** [comment]
Why this issue is closed now? What have i done? How can i reopen it?

**Comment by cdominpxp** [comment]
Sorry, got this issue out of focus.

in ext_localconf.php, i changed this:
```php
$TYPO3_CONF_VARS['BE']['AJAX']['txyagM1::getGalleryList'] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('yag').'Classes/Utility/Flexform/RecordSelector.php:user_Tx_Yag_Utility_Flexform_RecordSelector->getGallerySelectList';
$TYPO3_CONF_VARS['BE']['AJAX']['txyagM1::getAlbumList'] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('yag').'Classes/Utility/Flexform/RecordSelector.php:user_Tx_Yag_Utility_Flexform_RecordSelector->getAlbumSelectList';
$TYPO3_CONF_VARS['BE']['AJAX']['txyagM1::getImageList'] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('yag').'Classes/Utility/Flexform/RecordSelector.php:user_Tx_Yag_Utility_Flexform_RecordSelector->getImageSelectList';
```
to
```php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerAjaxHandler (
	'txyagM1::getGalleryList',
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('yag').'Classes/Utility/Flexform/RecordSelector.php:user_Tx_Yag_Utility_Flexform_RecordSelector->getGallerySelectList',
	false
);
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerAjaxHandler (
	'txyagM1::getAlbumList',
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('yag').'Classes/Utility/Flexform/RecordSelector.php:user_Tx_Yag_Utility_Flexform_RecordSelector->getAlbumSelectList',
	false
);
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerAjaxHandler (
	'txyagM1::getImageList',
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('yag').'Classes/Utility/Flexform/RecordSelector.php:user_Tx_Yag_Utility_Flexform_RecordSelector->getImageSelectList',
	false
);
```

**Comment by daniellienert** [comment]
I guess, thats exactly what I fixes 10 days ago in https://github.com/YAG-Gallery/yag/commit/abc8ba02a9c25e6d67d681eeb635b0c1e610ff65 ?

**Comment by cdominpxp** [comment]
Hi Daniel,
haven't looked at new commits after my holidays.
Exactly, so it is already fixed in master :+1:
