### ISSUE TITLE
Editing image: Fields author and tags are not saved

### ISSUE THREAD

**Issue by nilsrunde** [YAG-Gallery/yag#51]
1. When editing the field author my entry is not saved.
2. When editing the filed tags, not all tags are deleted at the same time, only a few. I need 3-4 times to delete all.

YAG 4.07
Extbase 2.1.1
Extlist 2.0.4

![fields not saved](https://cloud.githubusercontent.com/assets/6061814/10843665/8d574354-7efa-11e5-8160-fcbb1c06f531.png)

**Comment by daniellienert** [comment]
Hey @nilsrunde,
i don't know where your author field is coming from - this is not available in my version :)
I fixed the tags deletion problem with https://github.com/YAG-Gallery/yag/commit/604aed2903c8a9074df1bee69467e53f5256887d.

Thanks a lot for reporting!

Cheers, 
Daniel
