### ISSUE TITLE
Could not analyse class: "Tx_Yag_Extbase_Persistence_Backend" maybe not loaded or no autoloader?

### ISSUE THREAD

**Issue by metaxos** [YAG-Gallery/yag#52]
Hi

Trying to update from 7.5 to 7.6.2 (via clean, fresh install) just got data pages/tt_content/template and all of the yag.

In Backend i get following errors:
clicking on Extension Manager or Gallery BE-Module:
```
#1289386765: Could not analyse class: "Tx_Yag_Extbase_Persistence_Backend" maybe not loaded or no autoloader?
```

If I try to edit a image/album/gallery with the list:
```
#1444996537: Table tx_yag_domain_model_album field thumb points in foreign_selector or foreign_unique to field album of table tx_yag_domain_model_item, but this field is either not defined or is not of type select or group
```

Setup:
Typo3: 7.6.2
yag: 4.1.0
pt_extbase: 2.1.1
pt_extlist: 2.0.4
PHP 7

Any ideas?

**Comment by kersten** [comment]
does it work with php5.6?

**Comment by kabarakh** [comment]
TYPO3 7.x doesn't use any autoloader besides composer. Non-namespaced classes are not automagically loaded if the directory is not defined as a classmap in composer.json.

**Comment by kabarakh** [comment]
you could try out #53 to see if classmap definiton helps

**Comment by kersten** [comment]
@kabarakh thanks for pointing that out. And thanks for the #53 commit. But what if I don't use composer mode typo3? Where can I add the class map then?

**Comment by kersten** [comment]
ah i think adding:

```
'autoload' => 
  array(
    'classmap' => array('Classes')
  ),
```

To ext_emconf.php shoudl do the trick.

**Comment by metaxos** [comment]
I tried php 5.6 and the modification in ext_emconf.php regarding the autoload section, still the same issue.

**Comment by kersten** [comment]
@kabarakh The commit fixed that errro for me. @metaxos Did you clean your cache?

**Comment by kersten** [comment]
@kabarakh SOrry, forget to say. Switched my typo to composer mode. The change to composer.josn worked.

**Comment by kersten** [comment]
hm, seems not to work. The Error comes back. Sorry for the miss information

**Comment by kersten** [comment]
Ok, seems to work now. I moved completely to composer mode now. And voila the error has gone.

**Comment by metaxos** [comment]
@kersten 
Could you please share how to moved to composer mode?

**Comment by kersten** [comment]
@metaxos basically this guide helped me for the starting point: https://wiki.typo3.org/Composer

The little bit tricky thing is to get your extensions running again from composer only. I deleted them one by one and installed them back with composer after every single delete.

It is not that hard, but be aware of installing extensions with the extension manager then. This is not a good idea.

And do not use the 7.x-dev version. You should put ```7.6.*``` in your composer.json if you only want to stay on LTS.

**Comment by metaxos** [comment]
hi @kersten 
thank you. I got typo3 from composer. If I understand it correctly, then I need to get yag from composer and then install it via the "old" extension manager. How did you get the yag from composer?

**Comment by metaxos** [comment]
sorry but, get them from git and then just run composer install, that's it?

**Comment by kersten** [comment]
You have to install all extension with composer and only activate them in extension manager.

For using the suggested pull request your composer.json should look something like this:

```javascript
{
  "repositories": [
    {
      "type": "composer",
      "url": "http://composer.typo3.org/"
    }, {
      "type": "vcs",
      "url": "https://github.com/kabarakh/yag.git"
    }
  ],
  "name": "your-vendor/your-site",
  "require": {
    "typo3/cms": "7.6.*",
    "punktde/pt_extlist": "dev-master",
    "punktde/pt_extbase": "dev-master",
    "dl/yag": "dev-classmap_for_autoload"
  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms"
    }
  }
}
```

This important sections are the repository and the version of dl/yag. The repository sections tells composer to look in that repository from the new yag version. And the ```dev-classmap_for_autoload``` tells composer to use the branch with the fix.

I hope this works, I have an own composer repository for my stuff, so the vcs version above is only guessed.

**Comment by metaxos** [comment]
@kersten 
thank you. I got further on, unfortunately I got a "new" error when trying to add a new yag image:
````
#1437750231: The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA. 


TYPO3\CMS\Backend\Form\FormDataProvider\TcaInlineConfiguration::addInlineSelectorAndUniqueConfiguration(array, "thumb")
````

**Comment by kersten** [comment]
Yes I Know that error, didn't try to fix it yet. At my installation it only appears trying to use the list module. When I go over the gallery entry on the left mavigation I do not get the error, when did you got it?

**Comment by metaxos** [comment]
when using the list module I got the error. When I try to use the "gallery" module then I got another one:

````
#1: PHP Warning: Declaration of Tx_PtExtlist_Domain_Model_Filter_FilterFactory::injectObjectManager(TYPO3\CMS\Extbase\Object\ObjectManagerInterface $objectManager) should be compatible with Tx_PtExtlist_Domain_AbstractComponentFactory::injectObjectManager(TYPO3\CMS\Extbase\Object\ObjectManager $objectManager) in .../typo3conf/ext/pt_extlist/Classes/Domain/Model/Filter/FilterFactory.php line 38 (More information)
````

**Comment by kersten** [comment]
Are you using the dev-master version of pt_*

**Comment by metaxos** [comment]
yes, I copied the one you posted above

**Comment by kersten** [comment]
Did you run composer update after that?

**Comment by metaxos** [comment]
yes.
There where the tables cache_typo3temp_log and cache_imagesizes missing. I don't now why but creating them helped, now everything is working... thank you for your support.

**Comment by metaxos** [comment]
@kersten sorry a question, do you have "own" extension you get via composer... I cannot bring mine out of vendor into web/typo3conf/ext. How do you do this?

**Comment by kersten** [comment]
yes I have, but only for implementing a new feature. Could you please post your main composer.json

**Comment by metaxos** [comment]
here we go:
{
  "repositories": [
        {
            "type": "composer",
            "url": "http://composer.typo3.org/"
        },
        {
            "type": "package",
            "package": {
                "name": "metaxos/exaibbrplus",
                "version": "dev-2016",
                "source": {
                    "url": "https://metaxos@bitbucket.org/metaxos/exaibbrplus.git",
                    "type": "git",
                    "reference": "release/2016"
                }
            }
        }
    ],
  "name": "metaxos/exaibbrplus",
  "require": {
    "typo3/cms": "7.6.2",
    "bk2k/bootstrap-package" : "dev-master",
    "typo3-ter/compatibility6" : "7.6.0",
    "typo3-ter/extension-builder" : "7.6.0",
    "metaxos/exaibbrplus": "dev-2016"
  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": "web"
    }
  },
  "autoload": {
    "psr-4": {
      "Metaxos\\Exaibbrplus\\": "typo3conf/ext/exaibbrplus/Classes"
    }
  }
}

**Comment by kersten** [comment]
First you should put your extensions psr-4 autoload in your extension and put that ext in an extra composer package.

Second i can't see an entry ```"dl/yag": "dev-master" in your ```require``` section. Could you please add it there and call ```composer update``` or do you have it in your extension composer.json? If so, please paste the composer.json

**Comment by metaxos** [comment]
Thank you. Yes, the autoload is at the wrong place here, I missed that.
Sorry for being OT.
The problem I have is not about the YAG ext, but for my own ext hosted on bitbucket. The checkout works but the files are not placed at the correct place (in vendor instead of web).. Do I need the "post-update-cmd" -> script? Will the autoloading work then?

**Comment by kersten** [comment]
You need ```"type": "typo3-cms-extension"``` in your custom ext.

**Comment by metaxos** [comment]
this is my ext composer.json:

{
  "name": "Metaxos/exaibbrplus",
  "type": "typo3-cms-extension",
  "description": "Extension",
  "autoload": {
    "psr-4": {
      "Metaxos\\Exaibbrplus\\": "typo3conf/ext/exaibbrplus/Classes"
    }
  }
}


my project composer.json puts my ext in vendor/Metaxos/exaibbrplus instead of /web/typo3conf/ext/exaibbrplus

**Comment by kersten** [comment]
ok, here is one of my extension configs:

```javascript
{
  "name": "my/customext",
  "description": "custom ext for typo3",
  "type": "typo3-cms-extension",
  "version": "0.0.1",
  "require": {
    "typo3/cms-core": ">=6.2.0,<8.0",
  },
  "replace": {
    "extkey": "self.version",
    "typo3-ter/extkey": "self.version"
  },
  "autoload": {
    "psr-4": {
      "My\\CustomExt\\": "Classes/"
    }
  },
  "keywords": ["custom", "ext"],
  "homepage": "https://www.my-customext.com"
}
```

**Comment by metaxos** [comment]
thank you. still going in vendor. Would you provide your main composer.json?

**Comment by kersten** [comment]
sure...

```javascript
{
  "repositories": [
    {
      "type": "composer",
      "url": "http://composer.typo3.org/"
    }, {
      "type": "composer",
      "url": "https://my.custom-composer.com/"
    }
  ],
  "license": "proprietary",
  "name": "my/main-site",
  "description": "Main site",
  "require": {
    "typo3/cms": "7.6.*",
    "punktde/pt_extlist": "dev-master",
    "punktde/pt_extbase": "dev-master",
    "dl/yag": "dev-master",
    "my/customext": "dev-master"
  },
  "require-dev": {
    "mikey179/vfsStream": "1.6.0",
    "phpunit/phpunit": "~4.8.0"
  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": "webroot"
    }
  },
  "scripts": {
    "post-package-update": [
      "touch webroot/typo3temp/Cache/Code/cache_core/composer.tmp && rm webroot/typo3temp/Cache/Code/cache_core/*"
    ]
  }
}
```

**Comment by metaxos** [comment]
thanks
is the following your own "composer repo". This must be the one redirecting the checkout to the correct path, right? Is this a satis or lightwerk one?  Or are you going the "full" way like [here!](http://www.van-tomas.de/blog/project-automation-dependency-management-for-typo3cms-projects/)
```
    {
          "type": "composer",
          "url": "https://my.custom-composer.com/"
    }
```

**Comment by kersten** [comment]
no, this is a satis one. The only thing I have added was this: #53 nothing else.

**Comment by metaxos** [comment]
again thank you. I summarized up and move my question [here](http://stackoverflow.com/questions/34808337/composer-installs-own-typo3-extension-in-wrong-path)

**Comment by kersten** [comment]
Ok, thanks. Thats really a better place for such a question :) I've answered it there.

**Comment by kersten** [comment]
@daniellienert would you mind to check and merge #53?

**Comment by daniellienert** [comment]
Thanks a lot guys!
Sorry, currently my open source time is used up by neos development.
The PR is merged.
