### ISSUE TITLE
ETA for LTS 7 support

### ISSUE THREAD

**Issue by DanielRuf** [YAG-Gallery/yag#54]
Is there any ETA / plan on supporting the current LTS 7(.6) branch?

**Comment by kersten** [comment]
+1

**Comment by kersten** [comment]
@DanielRuf Currently I'm using it in a 7.6 branch. Have you got any problems?

**Comment by DanielRuf** [comment]
Didn't tst it, do you have any ißues in the logfile?

**Comment by daniellienert** [comment]
The current master definitely works with TYPO3 7.6 - which issues do you have @DanielRuf ?

**Comment by DanielRuf** [comment]
Ok, was not sure because the last update in the TER was many months ago and it is not updated to reflect, that LTS 7 is supported.

**Comment by DanielRuf** [comment]
Thanks for the update and new release in the TER =)
