### ISSUE TITLE
YAG with CoolUri

### ISSUE THREAD

**Issue by ProWebs** [YAG-Gallery/yag#72]
I'm using CoolUri and YAG but if i remove cHash from url the albums are broken and i'm getting a error message: Page Not Found Reason: Request parameters could not be validated (&cHash comparison failed).

Of course it would be also great to get a how to get nice urls on cooluri with yag, but this isn't so importent as getting it working without cHash, because i also don't wan't cHash on tt_news.

**Comment by daniellienert** [comment]
Hey @ProWebs - sorry I never use CoolUri and probably never will. So if you have any experience with it, don't hesitate to share it with us!
