### ISSUE TITLE
Gallery not build very well

### ISSUE THREAD

**Issue by mbch331** [YAG-Gallery/yag#93]
I'm using Yag with the isotope jquery theme. And sometimes when the gallery gets rebuild, the layout is a big mess (see attachement). How do I resolve this?
![afbeelding](https://cloud.githubusercontent.com/assets/12393536/21673861/4c6fb610-d32b-11e6-9017-7328f442bcd8.png)

**Comment by mwisgmbh** [comment]
Same Problem here. What can i do?
![isotope](https://cloud.githubusercontent.com/assets/25102309/21931189/5fa4a306-d99a-11e6-84d4-af7515317c8d.PNG)

**Comment by daniellienert** [comment]
Maybe the gallery script interferes with your sites javascript or CSS code. I'm afraid this is more an isotope related question and should be asked there. If you find a solution that can be integrated int the yag themepack - pull requests are always welcome.
